### ISSUE TITLE
The sample application doesn't run

### ISSUE THREAD

**Issue by wdcossey** [sampletext32/ImguiTestSample#1]
@sampletext32 

This sample app doesn't run as the textures and assets are missing, did you forget to commit this with the last commit?

**Comment by sampletext32** [comment]
Hi, this project is not an actual sample, I just cloned another person's repo (not forked). The setup stuff is basically taken from [this one](https://github.com/NogginBops/ImGui.NET_OpenTK_Sample). And other logic is adapted from [this one](https://github.com/TheCherno/Hazel).
If you want to see, how I actually made use of this - check [this repo](https://github.com/SCVE/SCVE), and exactly [here](https://github.com/SCVE/SCVE/blob/master/SCVE.Editor/EditorApp.cs)
